# Generated by Django 4.2.5 on 2023-10-20 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_weightgoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightgoal',
            old_name='Weight',
            new_name='weight',
        ),
    ]
