# Generated by Django 4.2.5 on 2023-10-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_alter_treino_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='editavel',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='UsuarioTreino',
        ),
    ]
