# Generated by Django 4.2.5 on 2023-10-30 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('H', 'Homem'), ('M', 'Mulher')], max_length=1)),
                ('idade', models.PositiveIntegerField(default=0)),
                ('altura', models.FloatField(default=0)),
                ('peso', models.FloatField(default=0)),
                ('metabolismo_basal', models.FloatField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
